---
- name: Dl and extract Apache Kafka
  hosts: ubuntu
  become: yes

  vars:
    download_url: "https://dlcdn.apache.org/kafka/4.0.0/kafka-4.0.0-src.tgz"
    download_path: "/tmp/kafka.tgz"
    extract_dir: "/opt/kafka"

  tasks:
    - name: Check that extract folder exists
      file:
        path: "{{ extract_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Dl Kafka archive
      get_url:
        url: "{{ download_url }}"
        dest: "{{ download_path }}"
        mode: '0644'

    - name: Extract to dir
      unarchive:
        src: "{{ download_path }}"
        dest: "{{ extract_dir }}"
        remote_src: yes
